name: 'html-reporter-azureblob-website'
description: 'HTML Test Results with history to publish to Azure Blob'
author: 'Pavan Mudigonda'
branding:
  icon: 'layout'
  color: 'green'
inputs:
  SAS:
    description: 'blob name'
    required: true
  container:
    description: 'Container name'
    required: false
    default: $web
  account_name:
    description: 'account name'
    required: false
  test_results:
    description: 'test result data dir'
    required: true
    default: 'test-results'
  results_history:
    description: 'Folder for results history'
    required: true
    default: 'results-history'
  keep_reports:
    description: 'Keep X last reports'
    required: false
    default: '20'    
  github_run_num:
    description: 'GitHub Actions build number'
    required: true
    default: ${{ github.run_number }}
  github_run_id:
    description: 'GitHub Actions run id'
    required: true
    default: ${{ github.run_id }}
  report_url:
    description: 'Use a custom URL instead of *.github.io'
    required: false
    default: ''
runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.sas }}
    - ${{ inputs.container }}
    - ${{ inputs.test_results }}
    - ${{ inputs.results_history }}
    - ${{ inputs.keep_reports }} 
    - ${{ inputs.report_url }}  
    - ${{ inputs.account_name }}
