name: test

on:
  workflow_dispatch:

jobs:

  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Git Repo
        uses: actions/checkout@v3
        
      - name: Create Test Results History
        uses: PavanMudigonda/html-reporter-azure-blob-website@v0.1
        with:
          test_results: test-results
          results_history: results-history
          keep_reports: 20
          connection_string: ${{ secrets.CONNECTION_STRING }}
          account_name: ${{ secrets.ACCOUNT_NAME }}
          container: ${{ secrets.CONTAINER }}

      - name: Post the link to the report
        if: always()
        uses: Sibz/github-status-action@v1
        with: 
            authToken: ${{secrets.GITHUB_TOKEN}}
            context: 'Test Results Link'
            state: 'success'
            sha: ${{ github.sha }}
            target_url: https://mudigonda.z13.web.core.windows.net/${{ github.run_number }}
